import type { Metadata } from 'next';
import { Audiowide } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import TopNav from '@/components/ui/nav/top-nav';
import { AuthProvider } from '@/AuthProvider';
import { VideoProvider } from '@/context/video';
import { Video } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const audiowide = Audiowide({
  variable: '--font-audiowide',
  subsets: ['latin'],
  weight: '400',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={`${audiowide.variable} antialiased`}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <VideoProvider>
              <TopNav />
              {children}
            </VideoProvider>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
